apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-auth-service
  namespace: toggle-master
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 5Gi
